# yaml-language-server: $schema=https://raw.githubusercontent.com/oxsecurity/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# Project-specific MegaLinter configuration
# Extends the base config from repo-operator
# Add custom linters or overrides below
# Add project-specific linters below:
# ENABLE_LINTERS:
#   - TYPESCRIPT_ES
#   - PYTHON_PYLINT

EXTENDS:
  - ".mega-linter-base.yml"
CONFIG_PROPERTIES_TO_APPEND:
  - "ENABLE_LINTERS"
  - "EXCLUDED_DIRECTORIES"
ENABLE_LINTERS:
  - "JAVASCRIPT_ES"
  - "JAVASCRIPT_PRETTIER"
  - "TYPESCRIPT_ES"
  - "TYPESCRIPT_PRETTIER"
EXCLUDED_DIRECTORIES:
  - coverage
  - dist
  - site
  - tmp

# Exclude intentionally invalid test fixtures from JSON linting
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: "fixtures/templates/invalid\\.json"
