import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RepoInfo } from './repo-detector.js';

export interface PROptions {
  repoInfo: RepoInfo;
  branchName: string;
  baseBranch: string;
  fileName: string;
  action: 'create' | 'update';
  workDir: string;
  dryRun?: boolean;
}

export interface PRResult {
  url?: string;
  success: boolean;
  message: string;
}

function loadPRTemplate(): string {
  // Try to find PR.md in the project root
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const templatePath = join(__dirname, '..', 'PR.md');

  if (existsSync(templatePath)) {
    return readFileSync(templatePath, 'utf-8');
  }

  // Fallback template
  return `## Summary
Automated sync of \`{{FILE_NAME}}\` configuration file.

## Changes
- {{ACTION}} \`{{FILE_NAME}}\` in repository root

---
*This PR was automatically generated by json-config-sync*`;
}

function formatPRBody(fileName: string, action: 'create' | 'update'): string {
  const template = loadPRTemplate();
  const actionText = action === 'create' ? 'Created' : 'Updated';

  return template
    .replace(/\{\{FILE_NAME\}\}/g, fileName)
    .replace(/\{\{ACTION\}\}/g, actionText);
}

export async function createPR(options: PROptions): Promise<PRResult> {
  const { repoInfo, branchName, baseBranch, fileName, action, workDir, dryRun } = options;

  const title = `chore: sync ${fileName}`;
  const body = formatPRBody(fileName, action);

  if (dryRun) {
    return {
      success: true,
      message: `[DRY RUN] Would create PR: "${title}"`,
    };
  }

  try {
    if (repoInfo.type === 'github') {
      return await createGitHubPR({ title, body, branchName, baseBranch, workDir });
    } else {
      return await createAzureDevOpsPR({
        title,
        body,
        branchName,
        baseBranch,
        repoInfo,
        workDir
      });
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      success: false,
      message: `Failed to create PR: ${message}`,
    };
  }
}

interface GitHubPROptions {
  title: string;
  body: string;
  branchName: string;
  baseBranch: string;
  workDir: string;
}

async function createGitHubPR(options: GitHubPROptions): Promise<PRResult> {
  const { title, body, branchName, baseBranch, workDir } = options;

  // Check if PR already exists
  try {
    const existingPR = execSync(
      `gh pr list --head "${branchName}" --json url --jq '.[0].url'`,
      { cwd: workDir, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    ).trim();

    if (existingPR) {
      return {
        url: existingPR,
        success: true,
        message: `PR already exists: ${existingPR}`,
      };
    }
  } catch {
    // No existing PR, continue to create
  }

  const result = execSync(
    `gh pr create --title "${title}" --body "${body.replace(/"/g, '\\"')}" --base "${baseBranch}" --head "${branchName}"`,
    { cwd: workDir, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
  ).trim();

  // Extract URL from output
  const urlMatch = result.match(/https:\/\/github\.com\/[^\s]+/);

  return {
    url: urlMatch?.[0] ?? result,
    success: true,
    message: 'PR created successfully',
  };
}

interface AzureDevOpsPROptions {
  title: string;
  body: string;
  branchName: string;
  baseBranch: string;
  repoInfo: RepoInfo;
  workDir: string;
}

async function createAzureDevOpsPR(options: AzureDevOpsPROptions): Promise<PRResult> {
  const { title, body, branchName, baseBranch, repoInfo, workDir } = options;

  // Check if PR already exists
  try {
    const existingPRs = execSync(
      `az repos pr list --repository "${repoInfo.repo}" --source-branch "${branchName}" --target-branch "${baseBranch}" --org "https://dev.azure.com/${repoInfo.organization}" --project "${repoInfo.project}" --query "[0].pullRequestId" -o tsv`,
      { cwd: workDir, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    ).trim();

    if (existingPRs) {
      const prUrl = `https://dev.azure.com/${repoInfo.organization}/${repoInfo.project}/_git/${repoInfo.repo}/pullrequest/${existingPRs}`;
      return {
        url: prUrl,
        success: true,
        message: `PR already exists: ${prUrl}`,
      };
    }
  } catch {
    // No existing PR, continue to create
  }

  const result = execSync(
    `az repos pr create --repository "${repoInfo.repo}" --source-branch "${branchName}" --target-branch "${baseBranch}" --title "${title}" --description "${body.replace(/"/g, '\\"')}" --org "https://dev.azure.com/${repoInfo.organization}" --project "${repoInfo.project}" --query "pullRequestId" -o tsv`,
    { cwd: workDir, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
  ).trim();

  const prUrl = `https://dev.azure.com/${repoInfo.organization}/${repoInfo.project}/_git/${repoInfo.repo}/pullrequest/${result}`;

  return {
    url: prUrl,
    success: true,
    message: 'PR created successfully',
  };
}
