import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { RepoInfo } from "./repo-detector.js";
import { getPRStrategy } from "./strategies/index.js";

// Re-export for backwards compatibility and testing
export { escapeShellArg } from "./shell-utils.js";

export interface PROptions {
  repoInfo: RepoInfo;
  branchName: string;
  baseBranch: string;
  fileName: string;
  action: "create" | "update";
  workDir: string;
  dryRun?: boolean;
}

export interface PRResult {
  url?: string;
  success: boolean;
  message: string;
}

function loadPRTemplate(): string {
  // Try to find PR.md in the project root
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const templatePath = join(__dirname, "..", "PR.md");

  if (existsSync(templatePath)) {
    return readFileSync(templatePath, "utf-8");
  }

  // Fallback template
  return `## Summary
Automated sync of \`{{FILE_NAME}}\` configuration file.

## Changes
- {{ACTION}} \`{{FILE_NAME}}\` in repository root

---
*This PR was automatically generated by json-config-sync*`;
}

export function formatPRBody(
  fileName: string,
  action: "create" | "update",
): string {
  const template = loadPRTemplate();
  const actionText = action === "create" ? "Created" : "Updated";

  return template
    .replace(/\{\{FILE_NAME\}\}/g, fileName)
    .replace(/\{\{ACTION\}\}/g, actionText);
}

export async function createPR(options: PROptions): Promise<PRResult> {
  const {
    repoInfo,
    branchName,
    baseBranch,
    fileName,
    action,
    workDir,
    dryRun,
  } = options;

  const title = `chore: sync ${fileName}`;
  const body = formatPRBody(fileName, action);

  if (dryRun) {
    return {
      success: true,
      message: `[DRY RUN] Would create PR: "${title}"`,
    };
  }

  // Get the appropriate strategy and execute
  const strategy = getPRStrategy(repoInfo);
  return strategy.execute({
    repoInfo,
    title,
    body,
    branchName,
    baseBranch,
    workDir,
  });
}
