# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
# See https://github.com/anthony-spruyt/repo-operator/blob/main/src/templates/.github/workflows/ci.yaml for template comments

name: "CI"
on:
  pull_request:
    branches:
      - "main"
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "labeled"
  push:
    branches:
      - "main"
permissions: {}
jobs:
  lint:
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_lint.yaml@b5ea71d349323dc58c83a432fff57f2d2bf1b39f"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  repo:
    needs:
      - "lint"
    permissions:
      contents: "read"
    uses: "./.github/workflows/ci-repo.yaml"
    secrets: "inherit"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  summary:
    needs:
      - "lint"
      - "repo"
    if: "always() && (github.event.action != 'labeled' || github.event.label.name == 'run-integration')"
    permissions:
      actions: "read"
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_summary.yaml@b5ea71d349323dc58c83a432fff57f2d2bf1b39f"
