# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
# See https://github.com/anthony-spruyt/repo-operator/blob/main/src/templates/.github/workflows/ci.yaml for template comments

name: "CI"
on:
  pull_request:
    branches:
      - "main"
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "labeled"
  push:
    branches:
      - "main"
permissions: {}
concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.action != 'labeled' && github.event.pull_request.number || github.run_id }}"
  cancel-in-progress: "${{ github.event_name == 'pull_request' && github.event.action != 'labeled' }}"
jobs:
  lint:
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_lint.yaml@55f5772eda61e5585fcfe7207d409f86ab130c5b"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  repo:
    needs:
      - "lint"
    permissions:
      contents: "read"
    uses: "./.github/workflows/ci-repo.yaml"
    secrets: "inherit"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  image:
    needs:
      - "lint"
      - "repo"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
    permissions:
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_images.yaml@55f5772eda61e5585fcfe7207d409f86ab130c5b"
  summary:
    needs:
      - "lint"
      - "repo"
      - "image"
      - "sonar"
    if: "always() && (github.event.action != 'labeled' || github.event.label.name == 'run-integration')"
    permissions:
      actions: "read"
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_summary.yaml@55f5772eda61e5585fcfe7207d409f86ab130c5b"
  sonar:
    permissions: {}
    uses: "anthony-spruyt/repo-operator/.github/workflows/_sonar-new-issues.yaml@55f5772eda61e5585fcfe7207d409f86ab130c5b"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
