# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
# See https://github.com/anthony-spruyt/repo-operator/blob/main/src/templates/.github/workflows/ci.yaml for template comments

name: "CI"
on:
  pull_request:
    branches:
      - "main"
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "labeled"
  push:
    branches:
      - "main"
permissions: {}
jobs:
  lint:
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_lint.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  repo:
    needs:
      - "lint"
    permissions:
      contents: "read"
    uses: "./.github/workflows/ci-repo.yaml"
    secrets: "inherit"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
  image:
    needs:
      - "lint"
      - "repo"
    if: "github.event.action != 'labeled' || github.event.label.name == 'run-integration'"
    permissions:
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_images.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
  summary:
    needs:
      - "lint"
      - "repo"
      - "image"
    if: "always() && (github.event.action != 'labeled' || github.event.label.name == 'run-integration')"
    permissions:
      actions: "read"
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_summary.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
